image: "harbor.dell.com/dojo-harbor/miniforge3"

stages:
  - Unit Test
  - Build Base Test
  - Build Orch Exec Test
  - Deploy to Test
  - Acceptance Test
  # - Release
  - Build Base Prod
  - Build Orch Exec

unit_test37:
  stage: Unit Test
  image: "harbor.dell.com/dojo-harbor/qre/test-base:3.7"

  script:
  - pip3 install . 
  - pytest tests/

unit_test38:
  stage: Unit Test
  image: "harbor.dell.com/dojo-harbor/qre/test-base:3.8"

  script:
  - pip3 install . 
  - pytest tests/

unit_test39:
  stage: Unit Test
  image: "harbor.dell.com/dojo-harbor/qre/test-base:3.9"

  script:
  - pip3 install . 
  - pytest tests/

# component:
#   stage: Unit Test
#   image: "harbor.dell.com/dojo-harbor/qre/component-base"

#   services:
#     - name: harbor.dell.com/dojo-harbor/mysql
#       alias: mysql
#       command: [ "--default-authentication-plugin=mysql_native_password" ]

#   variables: 
#     MYSQL_DATABASE: $MYSQL_DB
#     MYSQL_ROOT_PASSWORD: $MYSQL_PASS
#     DB_HOST: mysql
#     DB_PORT: 3306
#     DB_USER: root
#     DB_PASSWORD: password
#     DB_NAME: test

#   script:
#   - pip3 install . 
#   - pytest component_tests/

build_base_test:
  stage: Build Base Test
  image: "harbor.dell.com/dojo-harbor/docker"

  services:
  - name: harbor.dell.com/dojo-harbor/dind
    alias: thedockerhost
    entrypoint: ['dockerd-entrypoint.sh']
    command: ['--insecure-registry', 'harbor.dell.com' ]

  variables: 
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  services:
  - name: harbor.dell.com/dojo-harbor/dind
    alias: thedockerhost
    entrypoint: ['dockerd-entrypoint.sh']
    command: ['--insecure-registry', 'harbor.dell.com' ]

  variables: 
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker build --build-arg QRE_NS=qre-test ./ -t harbor.dell.com/dojo-harbor/qre-test/qre-base
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} harbor.dell.com
    - docker push harbor.dell.com/dojo-harbor/qre-test/qre-base

build_orch_test:
  stage: Build Orch Exec Test
  image: "harbor.dell.com/dojo-harbor/docker"

  services:
  - name: harbor.dell.com/dojo-harbor/dind
    alias: thedockerhost
    entrypoint: ['dockerd-entrypoint.sh']
    command: ['--insecure-registry', 'harbor.dell.com' ]

  variables: 
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - echo $PATH
    - docker build --build-arg QRE_NS=qre-test ./ -t harbor.dell.com/dojo-harbor/qre-test/qre-orchestrator
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} harbor.dell.com
    - docker push harbor.dell.com/dojo-harbor/qre-test/qre-orchestrator

build_exec_test:
  stage: Build Orch Exec Test
  image: "harbor.dell.com/dojo-harbor/docker"

  services:
  - name: harbor.dell.com/dojo-harbor/dind
    alias: thedockerhost
    entrypoint: ['dockerd-entrypoint.sh']
    command: ['--insecure-registry', 'harbor.dell.com' ]

  variables: 
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - echo $PATH
    - docker build --build-arg QRE_NS=qre-test ./ -t harbor.dell.com/dojo-harbor/qre-test/qre-executor
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} harbor.dell.com
    - docker push harbor.dell.com/dojo-harbor/qre-test/qre-executor

deploy_to_test:
  stage: Deploy to Test
  image: "harbor.dell.com/dojo-harbor/qre/deploy"

#TODO: Move certs to qre-secrets and use wget to grab instead of having in dir

  script:
    - mkdir -p ~/.kube
    - apt install wget
    - 'wget -O kube_config.yaml --header "PRIVATE-TOKEN: ${SECRETS_TOKEN}" http://10.238.22.159:8600/api/v4/projects/10/repository/files/kube_config.yaml/raw?ref=master'
    - ls -a
    - cp kube_config.yaml ~/.kube/config
    - cd server/deployments
    - source test.sh
    - cd ..
    - 'wget -O qrecerts.crt --header "PRIVATE-TOKEN: ${SECRETS_TOKEN}" http://10.238.22.159:8600/api/v4/projects/10/repository/files/qrecerts.crt/raw?ref=master'
    - 'wget -O ionq_simulator.crt --header "PRIVATE-TOKEN: ${SECRETS_TOKEN}" http://10.238.22.159:8600/api/v4/projects/10/repository/files/ionq_simulator.crt/raw?ref=master'
    - 'wget -O ionq_qpu.crt --header "PRIVATE-TOKEN: ${SECRETS_TOKEN}" http://10.238.22.159:8600/api/v4/projects/10/repository/files/ionq_qpu.crt/raw?ref=master'
    - export QRE_CERTS_DIR=.
    - make clean
    - make deploy
    - cd -
    - kubectl wait --for=condition=Ready pods --timeout=60s --all -n $(echo qre-test)

acceptance_test:
  stage: Acceptance Test
  image: "harbor.dell.com/dojo-harbor/qre/test-base:3.9"

  script:
    - python3 --version
    - pip3 install .
    - 'wget -O token.sh --header "PRIVATE-TOKEN: ${SECRETS_TOKEN}" http://10.238.22.159:8600/api/v4/projects/10/repository/files/token.sh/raw?ref=master'
    - source token.sh
    - export ACCEPTANCE_URL=http://qre-test.oro-sandbox-small1.k8s.cec.lab.emc.com
    - pytest acceptance_tests/
  

build_base:
  stage: Build Base Prod
  image: "harbor.dell.com/dojo-harbor/docker"

  services:
  - name: harbor.dell.com/dojo-harbor/dind
    alias: thedockerhost
    entrypoint: ['dockerd-entrypoint.sh']
    command: ['--insecure-registry', 'harbor.dell.com' ]

  variables: 
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker build --build-arg QRE_NS=qre ./ -t harbor.dell.com/dojo-harbor/qre/qre-base
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} harbor.dell.com
    - docker push harbor.dell.com/dojo-harbor/qre/qre-base

build_orch:
  stage: Build Orch Exec
  image: "harbor.dell.com/dojo-harbor/docker"

  services:
  - name: harbor.dell.com/dojo-harbor/dind
    alias: thedockerhost
    entrypoint: ['dockerd-entrypoint.sh']
    command: ['--insecure-registry', 'harbor.dell.com' ]

  variables: 
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - echo $PATH
    - docker build --build-arg QRE_NS=qre ./ -t harbor.dell.com/dojo-harbor/qre/qre-orchestrator
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} harbor.dell.com
    - docker push harbor.dell.com/dojo-harbor/qre/qre-orchestrator

build_exec:
  stage: Build Orch Exec
  image: "harbor.dell.com/dojo-harbor/docker"

  services:
  - name: harbor.dell.com/dojo-harbor/dind
    alias: thedockerhost
    entrypoint: ['dockerd-entrypoint.sh']
    command: ['--insecure-registry', 'harbor.dell.com' ]

  variables: 
    # Tell docker CLI how to talk to Docker daemon; see
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - echo $PATH
    - docker build --build-arg QRE_NS=qre ./ -t harbor.dell.com/dojo-harbor/qre/qre-executor
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} harbor.dell.com
    - docker push harbor.dell.com/dojo-harbor/qre/qre-executor

