
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qre-orchestrator
  namespace: ${QRE_NS}
spec:
  selector:
    matchLabels:
      app: qre-orchestrator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qre-orchestrator
    spec:
      serviceAccountName: qreorch
      containers:
        - name: qre-orchestrator
          image: ${DOCKER_REPO}/${QRE_NS}/orchestrator
          env:
          - name: DOCKER_REPO
            value: ${DOCKER_REPO}
          - name: DB_HOST
            value: ${DB_TYPE}
          - name: DB_PORT
            value: "${DB_PORT}"
          - name: DB_USER
            value: ${DB_USER}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-pw
                key: password
          - name: DB_NAME
            value: ${DB_DATABASE}                                    
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: certs
            mountPath: "/etc/qre_certs"
            readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: certs
          items:
          - key: qrecerts.crt
            path: qrecerts.crt
      # imagePullSecrets:
      #   - name: ${image_secret}

---

apiVersion: v1
kind: Service
metadata:
  name: qre-orchestrator
  namespace: ${QRE_NS}
spec:
  # loadBalancerIP: 100.80.243.207
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: qre-orchestrator
  # type: LoadBalancer

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: qre-ingress-orchestrator
  namespace: ${QRE_NS}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ${QRE_NS}.${KUBE_LOCATION}
    http:
      paths:
      - path: /
        backend:
          serviceName: qre-orchestrator
          servicePort: 8080
