apiVersion: v1
kind: Namespace
metadata:
  name: qre

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: qreorch
  namespace: qre

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: qre
  name: qreorch
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qreorch_binding
  namespace: qre
subjects:
- kind: ServiceAccount
  name: qreorch
  apiGroup: ""
roleRef:
  kind: Role
  name: qreorch
  apiGroup: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: qre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: qre
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: qre
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: harbor.dell.com/dojo-harbor/qre/mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: "MYSQL_DATABASE"
          value: "qre"
        - name: "MYSQL_USER"
          value: "qre"
        - name: "MYSQL_PASSWORD"
          value: "qre"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Pod
metadata:
  name: qre-orchestrator
  namespace: qre
  labels:
    app: qre-orchestrator
spec:
  serviceAccountName: qreorch
  containers:
    - name: qre-orchestrator
      image: harbor.dell.com/dojo-harbor/qre/qre-orchestrator
      env:
      - name: DB_HOST
        value: "mysql"
      - name: DB_PORT
        value: "3306"
      - name: DB_USER
        value: "qre"
      - name: DB_PASSWORD
        value: "qre"
      - name: DB_NAME
        value: "qre"
      ports:
      - containerPort: 8080
  imagePullSecrets:
    - name: ${image_secret}

---

apiVersion: v1
kind: Service
metadata:
  name: qre-orchestrator
  namespace: qre
spec:
  loadBalancerIP: 100.80.243.207
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: qre-orchestrator
  type: LoadBalancer
