groups:
- name: qiskit-emulator
  jobs:
  - unit_37
  - unit_38
  - unit_39
  - build_orchestrator
  - build_executor
  - deploy_to_test
  - acceptance_test
  - release

jobs:
- name: unit_37
  serial: true
  plan:
  - get: qiskit-runtime-emulator
    trigger: true
  - task: run-unit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          tag: 3.7
          username: {{repo_username}}
          password: {{repo_password}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: qiskit-runtime-emulator
      run:
        path: qiskit-runtime-emulator/ci/main/tasks/run-unit.sh

- name: unit_38
  serial: true
  plan:
  - get: qiskit-runtime-emulator
    trigger: true
  - task: run-unit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          tag: 3.8
          username: {{repo_username}}
          password: {{repo_password}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: qiskit-runtime-emulator
      run:
        path: qiskit-runtime-emulator/ci/main/tasks/run-unit.sh

- name: unit_39
  serial: true
  plan:
  - get: qiskit-runtime-emulator
    trigger: true
  - task: run-unit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          tag: 3.9
          username: {{repo_username}}
          password: {{repo_password}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: qiskit-runtime-emulator
      run:
        path: qiskit-runtime-emulator/ci/main/tasks/run-unit.sh

- name: build_orchestrator
  public: true
  serial: true
  plan:
  - get: qiskit-base-image
  - get: qiskit-runtime-emulator
    trigger: true
    passed: [unit_37, unit_38, unit_39]
  - put: orchestrator-image
    params:
      build: qiskit-runtime-emulator/server/orchestrator/

- name: build_executor
  public: true
  serial: true
  plan:
  - get: qiskit-base-image
  - get: qiskit-runtime-emulator
    trigger: true
    passed: [unit_37, unit_38, unit_39]
  - put: executor-image
    params:
      build: qiskit-runtime-emulator/server/executor/

- name: deploy_to_test
  serial: true
  plan:
  - get: qiskit-runtime-emulator
    trigger: true
    passed: [build_orchestrator, build_executor]
  - get: qre-secrets
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo_deploy}}
          tag: latest
          username: {{repo_username}}
          password: {{repo_password}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: qiskit-runtime-emulator
      - name: qre-secrets
      run:
        path: qiskit-runtime-emulator/ci/main/tasks/deploy.sh
    params:
      KUBECONFIG_FILE: |
        {{test_kubeconfig}}

- name: acceptance_test
  serial: true
  plan:
  - get: qiskit-runtime-emulator
    trigger: true
    passed: [deploy_to_test]
  - task: run-acceptance
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          tag: 3.9
          username: {{repo_username}}
          password: {{repo_password}}
          insecure_registries: [{{docker_registry}}]        
      inputs:
      - name: qiskit-runtime-emulator
      run:
        path: qiskit-runtime-emulator/ci/main/tasks/run-acceptance.sh
    params:
      ACCEPTANCE_URL: {{acceptance_url}}

- name: release
  serial: true
  plan:
  - get: qiskit-runtime-emulator
    trigger: true
  - get: qre-secrets
  - get: ibm-repo
  - task: release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          tag: 3.9
          username: {{repo_username}}
          password: {{repo_password}}
          insecure_registries: [{{docker_registry}}]
      inputs:
      - name: ibm-repo
      - name: qiskit-runtime-emulator
      - name: qre-secrets
      run:
        path: qiskit-runtime-emulator/ci/main/tasks/release.sh
      outputs:
      - name: qiskit-runtime-emulator
      - name: qre-secrets
  - put: qiskit-runtime-emulator
    params:
      repository: qiskit-runtime-emulator
  - put: qre-secrets
    params:
      repository: qre-secrets
  - put: qiskit-runtime-emulator
    params:
      repository: ibm-repo

resources:
- name: qiskit-runtime-emulator
  type: git
  icon: github-circle
  source: &github-secrets
    uri: git@eos2git.cec.lab.emc.com:OCTO/qiskit-runtime-emulator.git
    branch: master
    private_key: {{github_secret}}

- name: ibm-repo
  type: git
  icon: github-circle
  source: 
    uri: {{ibm_repo_uri}}
    branch: master
    private_key: {{ibm_repo_key}}

- name: qre-secrets
  type: git
  icon: github-circle
  source: 
    uri: git@eos2git.cec.lab.emc.com:DellEMC-Dojo/qre-secrets.git
    branch: master
    private_key: {{github_secret_secret}}

- name: qiskit-base-image
  type: docker-image
  icon: docker
  source:
    repository: {{docker_repo_qiskit}}
    username: {{repo_username}}
    password: {{repo_password}}
    insecure_registries: [{{docker_registry}}]

- name: orchestrator-image
  type: docker-image
  icon: docker
  source:
    repository: {{docker_repo_orchestrator}}
    username: {{repo_username}}
    password: {{repo_password}}
    insecure_registries: [{{docker_registry}}]

- name: executor-image
  type: docker-image
  icon: docker
  source:
    repository: {{docker_repo_executor}}
    username: {{repo_username}}
    password: {{repo_password}}
    insecure_registries: [{{docker_registry}}]

# - name: qiskit-runtime-emulator-version
#   type: semver
#   icon: update
#   source:
#     <<: *github-secrets
#     driver: git
#     file: ci/version